spring.application.name=ecolearn-backend

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:ecolearn_db}

server.port=8080

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

logging.level.org.springframework.data.mongodb=DEBUG

# GridFS
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# AI Service
ai.service.url=https://ecolearn-ai-service.onrender.com
ai.service.enabled=true
# Chatbot
groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.1-8b-instant
# Puntos
puntos.clasificacion.base=10
puntos.clasificacion.bonus-confianza=5
puntos.reto.completado=20
puntos.logro.bonus=15
puntos.nivel.umbral=100
puntos.confianza.umbral=0.75

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
logging.level.org.springframework.security=DEBUG
